"""Добавлено поле автора к продуктам

Revision ID: 905757535b3d
Revises: 018c6af5076d
Create Date: 2024-06-10 07:10:56.473998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '905757535b3d'
down_revision = '018c6af5076d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=64), nullable=True))
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('author')

    # ### end Alembic commands ###
