"""saved products2.0

Revision ID: bd008b9d3e37
Revises: 9ba9f0092d1f
Create Date: 2024-06-09 08:25:49.310422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd008b9d3e37'
down_revision = '9ba9f0092d1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_products', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
