"""order

Revision ID: eb4264c056d2
Revises: bd008b9d3e37
Create Date: 2024-06-09 09:35:07.180581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb4264c056d2'
down_revision = 'bd008b9d3e37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('comment', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_timestamp'), ['timestamp'], unique=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('status')
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_orders_timestamp'))
        batch_op.drop_column('timestamp')
        batch_op.drop_column('comment')
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
